### ISSUE TITLE
Doesn't find the center of the circle, intersection of two rays the split the circle

### ISSUE THREAD

**Issue by ripper234** [kasperpeulen/euclidthegame#337]
This should be a valid solution

![image](https://cloud.githubusercontent.com/assets/172282/11997408/6fd66eea-aa83-11e5-92c9-04c203990a10.png)

**Comment by ripper234** [comment]
AG splits the angle BAC
DG splits the angle EDF

**Comment by ripper234** [comment]
Another image, this time three different angle splitters meeting at the center G

![image](https://cloud.githubusercontent.com/assets/172282/11997440/018f8966-aa84-11e5-9044-e2b4a0c3adce.png)

**Comment by Hexstream** [comment]
I'm a bit rusty, but I think the problem is that your arbitrary (purple) points B, C, E and F are only _visually_ tangential to the circle, not _proven_ to be tangential _by construction_.

You could try zooming in and would probably find out that your points weren't perfectly tangential, but even if you zoomed in a lot and put every one of your arbitrary points on the right pixels, it still wouldn't be a valid solution. You need to construct a proof that will be valid even at "infinite resolution".

**Comment by ripper234** [comment]
You're right, the problem is that the rays are not tangent to the circle.
Sorry for the noise.
